import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { BiUserPlus } from 'react-icons/bi';
import Table from '../components/table';
import Form from '../components/Form';
import { useState } from 'react';
import handler from './api/cors';

// export async function getServerSideProps() {
//   const response = await fetch('http://localhost:3000/api/carpark');
//   const data = await response.json();
//   return {
//     props: { carparks: data },
//   };
// }

export default function Home() {
  const [visible, setVisible] = useState(false);
  const formHandler = () => {
    setVisible(!visible);
  };

  return (
    <section>
      <Head>
        <title>CRUD Application</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='py-5'>
        <h1 className='text-xl md:text-5xl text-center font-bold py-10'>
          Employee Management
        </h1>
        <div className='container mx-auto flex justify-between py-5 border-b'>
          <div className='left flex gap-3'>
            <button
              onClick={formHandler}
              className='flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-gray-50 hover:border-indigo-500 hover:text-gray-800'
            >
              Add Employee{' '}
              <span className='px-1'>
                <BiUserPlus size={23} />
              </span>
            </button>
          </div>
        </div>

        {visible ? <Form /> : <></>}

        <div className='container mx-auto py-5'>
          <Table />
        </div>
      </main>
    </section>
  );
}
